INSERT INTO QRTZ_LOCKS (SCHED_NAME, LOCK_NAME)
SELECT 'DEFAULT', 'TRIGGER_ACCESS' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM QRTZ_LOCKS WHERE SCHED_NAME='DEFAULT' AND LOCK_NAME='TRIGGER_ACCESS');

INSERT INTO QRTZ_LOCKS (SCHED_NAME, LOCK_NAME)
SELECT 'DEFAULT', 'STATE_ACCESS' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM QRTZ_LOCKS WHERE SCHED_NAME='DEFAULT' AND LOCK_NAME='STATE_ACCESS');